apiVersion: apps/v1
kind: Deployment
metadata:
  name: okdj0630
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okdj0630
  template:
    metadata:
      labels:
        app: okdj0630
    spec:
      containers:
      - image: okteto.dev/okdj0630:latest
        name: okdj0630
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a31562ca-faa0-40c7-aa35-896648beb22d"
        - name: Vless_Path
          value: "/yujhjyhd"
        - name: Vmess_UUID
          value: "551680a1-389d-480b-afa4-dc9676fb1a4b"
        - name: Vmess_Path
          value: "/fiowe"
        - name: Share_Path
          value: "/v2link"
