apiVersion: v1
kind: Service
metadata:
  name: okdj0630
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okdj0630"
    port: 8080
  selector:
    app: okdj0630
